Table "assets_available" {
  "asset" varchar(255) [not null]
  "class" varchar(255) [not null]
  "altname" varchar(255) [default: NULL]
  "decimals" int(10) [not null]
  "display_decimals" int(10) [not null]
  "active" tinyint(1) [not null, default: "0"]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]

  Indexes {
    asset [unique, name: "assets_available_asset_unique"]
  }
}
